# Changes to make all backgrounds black while preserving visual hierarchy

[mgr]
count_copied   = { fg = "green", bg = "black", bold = true }
count_cut      = { fg = "red", bg = "black", bold = true }
count_selected = { fg = "yellow", bg = "black", bold = true }
preview_hovered = { fg = "white", bg = "darkgray", underline = false }

[tabs]
active   = { fg = "white", bg = "darkgray", bold = true }
inactive = { fg = "blue", bg = "black" }

[mode]
normal_main = { fg = "blue", bg = "black", bold = true }
normal_alt  = { fg = "blue", bg = "black" }
select_main = { fg = "red", bg = "black", bold = true }
select_alt  = { fg = "red", bg = "black" }
unset_main = { fg = "red", bg = "black", bold = true }
unset_alt  = { fg = "red", bg = "black" }

[status]
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

[which]
mask = { bg = "black" }

[help]
footer = { fg = "white", bg = "black", bold = true }

[filetype]
rules = [
	{ mime = "image/*", fg = "yellow" },
	{ mime = "{audio,video}/*", fg = "magenta" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
	{ mime = "application/{pdf,doc,rtf}", fg = "cyan" },
	{ name = "*", is = "orphan", fg="red", bg = "black" },
	{ name = "*", is = "exec"  , fg = "green" },
	{ name = "*", is = "dummy", fg="red", bg = "black" },
	{ name = "*/", is = "dummy", fg="red", bg = "black" },
	{ name = "*/", fg = "blue" }
]
